name: Contribution Form Filled label verification
on:
  pull_request:
    types: [opened, synchronize, labeled, unlabeled]

jobs:
  contribution_form_filled_verification:
    runs-on: ubuntu-latest
    if: github.repository == 'demisto/content' && github.event.pull_request.head.repo.fork == true && contains(github.head_ref, 'xsoar-bot-contrib-ContributionTestPack') == false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Print Context
        run: |
          echo "$GITHUB_CONTEXT"
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
      - name: Install Python Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Check if "Contribution Form Filled" label exists in PR
        if: contains(github.event.pull_request.labels.*.name, 'Contribution Form Filled') == true
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "Contribution Form Filled label exists in PR: $PR_NUMBER"
          exit 0
      - name: Check if contribution form needs to be filled
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Checking f contribution form needs to be filled for PR: $PR_NUMBER"
          cd Utils/github_workflow_scripts
          pipenv install --dev
          pipenv run ./check_if_needs_to_fill_contribution_form.py --pr_number $PR_NUMBER --github_token $GITHUB_TOKEN
          
